pipeline {
    agent any

    environment {
        IMAGE_NAME = "johnvelan/devops-backend"   // 🔁 Your DockerHub repo
        IMAGE_TAG  = "${env.BUILD_NUMBER}"
        DEPLOYMENT_NAME = "backend-deployment"
        CONTAINER_NAME  = "backend"
        NAMESPACE = "devops-project"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Kumaranvelan/devops-end-to-end-project'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG ./app/backend'
                sh 'docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest'
            }
        }

        stage('Docker Hub Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds-new',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
            }
        }

        stage('Push Image') {
            steps {
                sh 'docker push $IMAGE_NAME:$IMAGE_TAG'
                sh 'docker push $IMAGE_NAME:latest'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh """
                kubectl set image deployment/$DEPLOYMENT_NAME \
                $CONTAINER_NAME=$IMAGE_NAME:$IMAGE_TAG \
                -n $NAMESPACE
                """

                sh 'kubectl rollout status deployment/$DEPLOYMENT_NAME -n $NAMESPACE'
            }
        }
    }

    post {
        success {
            echo "✅ Deployment Successful!"
            echo "Image Deployed: $IMAGE_NAME:$IMAGE_TAG"
        }
        failure {
            echo "❌ Pipeline Failed!"
        }
    }
}
